language: python

sudo: false

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO_VERSION=1.3
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8

install:
  - pip install -r requirements.txt
  - pip install -U Django==$DJANGO_VERSION

script: python runtests.py
